server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: idle-fcfs-producer
  profiles:
    active: local
  jackson:
    default-property-inclusion: non_null
  config:
    import:
      - classpath:properties/aws.yml
      - classpath:properties/event.yml

logging:
  level:
    root: INFO